require('dotenv').config();
const { MongoClient, ServerApiVersion } = require('mongodb');

const uri = `mongodb+srv://${process.env.DB_USER}:${process.env.DB_PASS}@cluster0.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0`;

const pets = [
  {
    name: 'Buddy',
    species: 'dog',
    breed: 'Golden Retriever',
    age: 2,
    gender: 'male',
    location: 'New York, NY',
    adoptionFee: 150,
    vaccinationStatus: true,
    healthStatus: 'excellent',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop',
    description: 'Buddy is a friendly and energetic Golden Retriever who loves to play fetch and cuddle on the couch. He is great with kids and other dogs. Fully vaccinated and house-trained.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2024-12-01'),
  },
  {
    name: 'Luna',
    species: 'cat',
    breed: 'Persian',
    age: 3,
    gender: 'female',
    location: 'Los Angeles, CA',
    adoptionFee: 100,
    vaccinationStatus: true,
    healthStatus: 'excellent',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&h=400&fit=crop',
    description: 'Luna is a calm and affectionate Persian cat who enjoys lounging in sunny spots. She is perfect for apartment living and gets along well with other cats.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2024-12-03'),
  },
  {
    name: 'Max',
    species: 'dog',
    breed: 'German Shepherd',
    age: 4,
    gender: 'male',
    location: 'Chicago, IL',
    adoptionFee: 200,
    vaccinationStatus: true,
    healthStatus: 'excellent',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=600&h=400&fit=crop',
    description: 'Max is an intelligent and loyal German Shepherd. He has basic obedience training and loves outdoor adventures. Ideal for an active family with a yard.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2024-12-05'),
  },
  {
    name: 'Bella',
    species: 'cat',
    breed: 'Maine Coon',
    age: 1,
    gender: 'female',
    location: 'Houston, TX',
    adoptionFee: 120,
    vaccinationStatus: true,
    healthStatus: 'excellent',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?w=600&h=400&fit=crop',
    description: 'Bella is a playful and curious Maine Coon kitten. She loves interactive toys and is very social. She would thrive in a home with plenty of playtime and affection.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2024-12-07'),
  },
  {
    name: 'Charlie',
    species: 'dog',
    breed: 'Beagle',
    age: 3,
    gender: 'male',
    location: 'Phoenix, AZ',
    adoptionFee: 130,
    vaccinationStatus: true,
    healthStatus: 'good',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=600&h=400&fit=crop',
    description: 'Charlie is a cheerful Beagle with a great nose for adventure. He loves walks, sniffing everything in sight, and playing with kids. He is well socialized and friendly.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2024-12-09'),
  },
  {
    name: 'Mango',
    species: 'bird',
    breed: 'African Grey Parrot',
    age: 5,
    gender: 'male',
    location: 'Miami, FL',
    adoptionFee: 500,
    vaccinationStatus: false,
    healthStatus: 'excellent',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=600&h=400&fit=crop',
    description: 'Mango is a highly intelligent African Grey Parrot who can mimic over 50 words and phrases. He enjoys social interaction and mental stimulation. Needs an experienced bird owner.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2024-12-11'),
  },
  {
    name: 'Daisy',
    species: 'rabbit',
    breed: 'Holland Lop',
    age: 1,
    gender: 'female',
    location: 'Seattle, WA',
    adoptionFee: 60,
    vaccinationStatus: false,
    healthStatus: 'excellent',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=600&h=400&fit=crop',
    description: 'Daisy is an adorable Holland Lop rabbit with floppy ears and a gentle temperament. She loves fresh vegetables and being gently handled. Perfect for a quiet home.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2024-12-13'),
  },
  {
    name: 'Rocky',
    species: 'dog',
    breed: 'Labrador Retriever',
    age: 5,
    gender: 'male',
    location: 'Denver, CO',
    adoptionFee: 180,
    vaccinationStatus: true,
    healthStatus: 'good',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&h=400&fit=crop',
    description: 'Rocky is a laid-back Labrador who loves swimming and fetching balls. He is great with families and gets along with other pets. Fully house-trained and leash-trained.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2024-12-15'),
  },
  {
    name: 'Whiskers',
    species: 'cat',
    breed: 'Tabby',
    age: 4,
    gender: 'male',
    location: 'Boston, MA',
    adoptionFee: 0,
    vaccinationStatus: true,
    healthStatus: 'good',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?w=600&h=400&fit=crop',
    description: 'Whiskers is a gentle tabby cat looking for a quiet home. He loves sitting by windows, watching birds, and being petted. He is fully litter-trained and very low-maintenance.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2024-12-17'),
  },
  {
    name: 'Coco',
    species: 'dog',
    breed: 'Poodle',
    age: 2,
    gender: 'female',
    location: 'San Francisco, CA',
    adoptionFee: 220,
    vaccinationStatus: true,
    healthStatus: 'excellent',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1601979031925-424e53b6caaa?w=600&h=400&fit=crop',
    description: 'Coco is a charming miniature Poodle who is hypoallergenic and incredibly smart. She has completed basic obedience training and loves to show off her tricks.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2024-12-19'),
  },
  {
    name: 'Oliver',
    species: 'cat',
    breed: 'British Shorthair',
    age: 2,
    gender: 'male',
    location: 'Austin, TX',
    adoptionFee: 150,
    vaccinationStatus: true,
    healthStatus: 'excellent',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=600&h=400&fit=crop',
    description: 'Oliver is a plush British Shorthair with a calm and dignified personality. He enjoys a quiet environment and is perfectly happy as an indoor cat. Great for working professionals.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2024-12-21'),
  },
  {
    name: 'Nemo',
    species: 'fish',
    breed: 'Clownfish',
    age: 1,
    gender: 'male',
    location: 'San Diego, CA',
    adoptionFee: 20,
    vaccinationStatus: false,
    healthStatus: 'excellent',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&h=400&fit=crop',
    description: 'Nemo is a vibrant clownfish living in a healthy tank. Perfect starter pet for families. Comes with a small tank setup guide. Very low maintenance and mesmerizing to watch.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2024-12-23'),
  },
  {
    name: 'Simba',
    species: 'cat',
    breed: 'Bengal',
    age: 1,
    gender: 'male',
    location: 'Nashville, TN',
    adoptionFee: 200,
    vaccinationStatus: true,
    healthStatus: 'excellent',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1561948955-570b270e7c36?w=600&h=400&fit=crop',
    description: 'Simba is a stunning Bengal kitten with wild-looking spots and an energetic personality. He loves to climb, explore, and play. Needs an active household that can keep up with his energy.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2025-01-02'),
  },
  {
    name: 'Cooper',
    species: 'dog',
    breed: 'Border Collie',
    age: 3,
    gender: 'male',
    location: 'Portland, OR',
    adoptionFee: 175,
    vaccinationStatus: true,
    healthStatus: 'excellent',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?w=600&h=400&fit=crop',
    description: 'Cooper is a brilliant Border Collie who is happiest when he has a job to do. He excels at agility, frisbee, and learning new tricks. Best suited for an active owner or family.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2025-01-05'),
  },
  {
    name: 'Pearl',
    species: 'hamster',
    breed: 'Syrian Hamster',
    age: 1,
    gender: 'female',
    location: 'Atlanta, GA',
    adoptionFee: 15,
    vaccinationStatus: false,
    healthStatus: 'excellent',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=600&h=400&fit=crop',
    description: 'Pearl is a fluffy Syrian hamster who loves running on her wheel and burrowing in bedding. She is tame and easy to handle. Perfect first pet for children.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2025-01-08'),
  },
  {
    name: 'Zeus',
    species: 'dog',
    breed: 'Husky',
    age: 2,
    gender: 'male',
    location: 'Minneapolis, MN',
    adoptionFee: 250,
    vaccinationStatus: true,
    healthStatus: 'excellent',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=600&h=400&fit=crop',
    description: 'Zeus is a majestic Siberian Husky with striking blue eyes. He is energetic and loves cold weather. Requires daily exercise and mental stimulation. An amazing companion for outdoor lovers.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2025-01-10'),
  },
  {
    name: 'Lily',
    species: 'cat',
    breed: 'Siamese',
    age: 3,
    gender: 'female',
    location: 'Las Vegas, NV',
    adoptionFee: 110,
    vaccinationStatus: true,
    healthStatus: 'good',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=600&h=400&fit=crop',
    description: 'Lily is a vocal and affectionate Siamese cat who loves to have conversations with her humans. She bonds deeply with her owner and does best as the only pet in the home.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2025-01-12'),
  },
  {
    name: 'Ginger',
    species: 'rabbit',
    breed: 'Angora',
    age: 2,
    gender: 'female',
    location: 'Philadelphia, PA',
    adoptionFee: 75,
    vaccinationStatus: false,
    healthStatus: 'good',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1518796745738-41048802f99a?w=600&h=400&fit=crop',
    description: 'Ginger is a fluffy Angora rabbit with silky soft fur. She is gentle and loves to be groomed. Requires regular brushing to keep her coat healthy. Very calm and quiet.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2025-01-14'),
  },
  {
    name: 'Duke',
    species: 'dog',
    breed: 'Rottweiler',
    age: 4,
    gender: 'male',
    location: 'Dallas, TX',
    adoptionFee: 200,
    vaccinationStatus: true,
    healthStatus: 'good',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop&q=80&sat=-50',
    description: 'Duke is a gentle giant Rottweiler who is loyal and protective of his family. Despite his size he is very calm indoors. He has had obedience training and is great with older children.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2025-01-16'),
  },
  {
    name: 'Kiwi',
    species: 'bird',
    breed: 'Budgerigar',
    age: 1,
    gender: 'female',
    location: 'Orlando, FL',
    adoptionFee: 35,
    vaccinationStatus: false,
    healthStatus: 'excellent',
    status: 'available',
    image: 'https://images.unsplash.com/photo-1452570053594-1b985d6ea890?w=600&h=400&fit=crop',
    description: 'Kiwi is a bright and cheerful budgerigar who loves to sing and chirp. She is hand-tamed and enjoys sitting on shoulders. A wonderful and affordable companion for bird lovers.',
    ownerEmail: 'shelter@petadoption.com',
    createdAt: new Date('2025-01-18'),
  },
];

async function seed() {
  const client = new MongoClient(uri, {
    serverApi: { version: '1', strict: true, deprecationErrors: true },
  });

  try {
    await client.connect();
    const db = client.db('petAdoptionDB');
    const collection = db.collection('pets');

    // Clear existing pets added by shelter account only
    await collection.deleteMany({ ownerEmail: 'shelter@petadoption.com' });
    console.log('Cleared existing seed pets');

    const result = await collection.insertMany(pets);
    console.log(`Successfully inserted ${result.insertedCount} pets`);

    // Verify
    const count = await collection.countDocuments({ status: 'available' });
    console.log(`Total available pets in DB: ${count}`);

  } catch (err) {
    console.error('Seed error:', err);
  } finally {
    await client.close();
  }
}

seed();
